merge from HEAD branch

diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -83,11 +83,12 @@ do_diff()
 die ()
 {
 	local status=$1
+	[ -e "$tmp_files" ] && rm -f $tmp_files
 	[ -n "$workdir" ] && rm -rf $workdir
 	exit $status
 }
 
-options=`getopt -o p:P:c:Rzh --long diff: -- "$@"`
+options=`getopt -o p:P:c:Rzh --long diff:,snapshot -- "$@"`
 
 if [ $? -ne 0 ]
 then
@@ -106,7 +107,8 @@ do
 		last_patch=$(stripit $2)
 		shift 2 ;;
 	-c)
-		opt_combine=$(stripit $2)
+		opt_combine=1
+		first_patch=$(stripit $2)
 		shift 2 ;;
 	-R)
 		opt_reverse=1
@@ -116,8 +118,12 @@ do
 		shift ;;
 	-h)
 		usage -h ;;
+	--snapshot)
+		opt_snapshot=1
+		snap_subdir=.snap
+		shift ;;
 	--diff)
-		opt_diff=$2
+		opt_diff="$2"
 		shift 2 ;;
 	--)
 		shift
@@ -127,9 +133,9 @@ done
 
 opt_files=( "$@" )
 
-if [ -n "$opt_combine" -a -n "$opt_relative" ]
+if [ $[0$opt_combine + 0$opt_snapshot + 0$opt_relative] -gt 1 ]
 then
-	echo $"Options \`-c patch' and \`-z' cannot be combined."
+	echo $"Options \`-c patch', \`--snapshot', and \`-z' cannot be combined."
 	die 1
 fi
 
@@ -159,63 +165,60 @@ then
 	die 1
 fi
 
+trap "die 1" SIGTERM
+
+tmp_files=$(gen_tempfile)
+exec 4> $tmp_files  # open $tmp_files
+
+if [ -n "$opt_snapshot" -a ${#opt_files[@]} -eq 0 ]
+then
+	# Add all files in the snapshot into the file list (they may all
+	# have changed).
+	while read file
+	do
+		echo "${file#.pc/$snap_subdir/}" >&4
+	done \
+	< <(find .pc/$snap_subdir -type f)
+	# Also look at all patches that are currently applied.
+	opt_combine=1
+	first_patch="$(applied_patches | head -n 1)"
+fi
+
 if [ -n "$opt_combine" ]
 then
-	if ! refresh_patches_per_file
-	then
-		echo $"refresh_patches_per_file failed."
-		die 1
-	fi
-	
 	set -- $(patches_before $last_patch) $last_patch
-	if [ "x$opt_combine" != "x-" ]
+	if [ "$first_patch" != "-" ]
 	then
-		while [ $# -ge 1 -a "$1" != "$opt_combine" ]
+		while [ $# -ge 1 -a "$1" != "$first_patch" ]
 		do
 			shift
 		done
 		if [ $# -eq 0 ]
 		then
-			echo $"Patch $opt_combine not applied before $last_patch."
+			echo $"Patch $first_patch not applied before $last_patch."
 			die 1
 		fi
 	fi
-	
-	while read file first garbage
-	do
-		if [ ${#opt_files[@]} -gt 0 ] && \
-		   ! in_array "$file" "${opt_files[@]}"
-		then
-			continue
-		fi
-		patches[${#patches[@]}]="$first"
-		files[${#files[@]}]="$file"
-	done \
-	< <(modified_files -- "$@")
+	patches=( $@ )
 else
-	for file in $(files_in_patch $last_patch)
+	patches=( $last_patch )
+fi
+
+for patch in ${patches[@]}
+do
+	for file in $(files_in_patch $patch)
 	do
 		if [ ${#opt_files[@]} -gt 0 ] && \
 		   ! in_array "$file" "${opt_files[@]}"
 		then
 			continue
 		fi
-		files[${#files[@]}]="$file"
-	done
-fi
+		echo "$file" >&4
+	done < <(files_in_patch $patch)
+done
 
-if [ ${#opt_files[@]} -gt 0 ]
-then
-	for file in "${opt_files[@]}"
-	do
-		if ! in_array "$file" "${files[@]}"
-		then
-			echo $"File $file is not being modified."
-		fi
-	done
-fi
-
-trap "die 1" SIGTERM
+exec 4>&-  # close $tmp_files
+files=( $(sort -u $tmp_files) )
 
 if [ -n "$opt_relative" ]
 then
@@ -266,10 +269,24 @@ then
 	fi
 fi
 
-for ((i=0; i<${#files[@]}; i++))
+for file in "${files[@]}"
 do
-	file="${files[$i]}"
-	first_patch=${patches[$i]:-$last_patch}
+	if [ -n "$opt_snapshot" -a -e ".pc/$snap_subdir/$file" ]
+	then
+		old_file=".pc/$snap_subdir/$file"
+	elif [ -n "$opt_relative" ]
+	then
+		old_file="$workdir/$file"
+	else
+		patch="$(first_modified_by $file ${patches[@]})"
+		if [ -z "$patch" ]
+		then
+			[ -z "$opt_snapshot" ] \
+			&& echo $"File $file is not being modified."
+			continue
+		fi
+		old_file="$(backup_file_name $patch $file)"
+	fi
 
 	next_patch=$(next_patch_for_file $last_patch $file)
 	if [ -z "$next_patch" ]
@@ -280,13 +297,7 @@ do
 		files_were_shadowed=1
 	fi
 
-	if [ -z "$opt_relative" ]
-	then
-		old_file=$(backup_file_name $first_patch $file)
-		do_diff $file $old_file $new_file
-	else
-		do_diff $file "$workdir/$file" $new_file
-	fi
+	do_diff "$file" "$old_file" "$new_file"
 
 	if [ $? -ne 0 ]
 	then
